version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      while ! nc -z minio 9000; do
        sleep 1;
      done;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/mybucket;
      mc cp /data/example.txt myminio/mybucket;
      mc ls myminio/mybucket;
      tail -f /dev/null
      "
    volumes:
      - ./client-data:/data

volumes:
  minio-data:
  client-data: